name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      GITLAB_PROJECT: ${{ secrets.GITLAB_PROJECT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Get commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV


      - name: Build with Gradle
        run: ./gradlew jib
